const InterviewAI = (() => {
  const defaultUser = { name: 'Rishabh Singh', email: 'rishabh@example.com', role: 'Frontend Developer', experience: 'Fresher' };
  const questions = [
    { id: 1, category: 'JavaScript', difficulty: 'Easy', question: 'Which method adds an element to the end of a JavaScript array?', answer: 'push()', explanation: 'push() appends one or more elements to the end of an array.' },
    { id: 2, category: 'JavaScript', difficulty: 'Medium', question: 'What is a closure in JavaScript?', answer: 'A function bundled with its lexical environment', explanation: 'A closure retains access to variables from its outer scope even after that scope has finished.' },
    { id: 3, category: 'HTML / CSS', difficulty: 'Easy', question: 'What is the purpose of semantic HTML?', answer: 'To give content meaningful structure', explanation: 'Semantic elements communicate structure to browsers, assistive technology, and future developers.' },
    { id: 4, category: 'Data Structures', difficulty: 'Medium', question: 'What is the average time complexity of lookup in a hash table?', answer: 'O(1)', explanation: 'With a good hash function and low collisions, lookup is constant time on average.' },
    { id: 5, category: 'DBMS', difficulty: 'Hard', question: 'What does database normalization help prevent?', answer: 'Redundancy and update anomalies', explanation: 'Normalization organizes related data to reduce duplication and protect consistency.' },
    { id: 6, category: 'Algorithms', difficulty: 'Medium', question: 'Which traversal visits a binary search tree in sorted order?', answer: 'In-order traversal', explanation: 'In-order traversal visits left subtree, node, then right subtree, producing sorted values in a BST.' },
    { id: 7, category: 'Python', difficulty: 'Easy', question: 'Which Python data type stores key-value pairs?', answer: 'Dictionary', explanation: 'Dictionaries map immutable keys to values and are optimized for lookup.' },
    { id: 8, category: 'JavaScript', difficulty: 'Hard', question: 'How does const differ from let?', answer: 'const prevents reassignment of the binding', explanation: 'const bindings cannot be reassigned, though referenced objects may still be mutable.' },
    { id: 9, category: 'JavaScript', difficulty: 'Medium', question: 'What does the event loop coordinate?', answer: 'The call stack and asynchronous task queues', explanation: 'The event loop moves queued callbacks to the stack when JavaScript is ready.' },
    { id: 10, category: 'JavaScript', difficulty: 'Easy', question: 'What value does typeof null return?', answer: 'object', explanation: 'typeof null returns object for historical compatibility in JavaScript.' },
    { id: 11, category: 'JavaScript', difficulty: 'Hard', question: 'What is event delegation?', answer: 'Handling child events from a shared ancestor', explanation: 'Delegation uses bubbling to manage many descendants with one listener.' },
    { id: 12, category: 'JavaScript', difficulty: 'Medium', question: 'What is the difference between map and forEach?', answer: 'map returns a transformed array; forEach does not', explanation: 'map creates a new array from callback results, while forEach is used for side effects.' },
    { id: 13, category: 'JavaScript', difficulty: 'Medium', question: 'What does Promise.all do when one promise rejects?', answer: 'The combined promise rejects', explanation: 'Promise.all fulfills only when every input fulfills and rejects on the first rejection.' },
    { id: 14, category: 'HTML / CSS', difficulty: 'Easy', question: 'Why is the alt attribute important on images?', answer: 'It provides an accessible text alternative', explanation: 'Alternative text helps screen-reader users and appears when an image cannot load.' },
    { id: 15, category: 'HTML / CSS', difficulty: 'Medium', question: 'What does CSS specificity determine?', answer: 'Which matching rule wins', explanation: 'Specificity resolves competing selectors before source order is considered.' },
    { id: 16, category: 'HTML / CSS', difficulty: 'Easy', question: 'What is the purpose of a label element?', answer: 'To associate text with a form control', explanation: 'A label improves usability and lets assistive technology identify the control.' },
    { id: 17, category: 'HTML / CSS', difficulty: 'Medium', question: 'What does display: flex create?', answer: 'A flex formatting context', explanation: 'Flexbox lays out direct children along a main axis and cross axis.' },
    { id: 18, category: 'HTML / CSS', difficulty: 'Hard', question: 'Why use CSS custom properties?', answer: 'To reuse and update design values', explanation: 'Custom properties provide runtime variables that support consistent themes.' },
    { id: 19, category: 'HTML / CSS', difficulty: 'Medium', question: 'What is the CSS box model?', answer: 'Content, padding, border, and margin', explanation: 'These layers determine an element’s rendered size and surrounding space.' },
    { id: 20, category: 'HTML / CSS', difficulty: 'Easy', question: 'Which HTML element represents the primary page content?', answer: 'main', explanation: 'The main element identifies the dominant content unique to a document.' },
    { id: 21, category: 'Data Structures', difficulty: 'Easy', question: 'Which data structure follows last-in, first-out order?', answer: 'Stack', explanation: 'A stack removes the most recently added item first.' },
    { id: 22, category: 'Data Structures', difficulty: 'Easy', question: 'Which data structure follows first-in, first-out order?', answer: 'Queue', explanation: 'A queue removes items in the same order they were inserted.' },
    { id: 23, category: 'Data Structures', difficulty: 'Medium', question: 'What is the main advantage of a linked list over an array?', answer: 'Efficient insertion when a node reference is known', explanation: 'Linked lists avoid shifting later elements for local insertions.' },
    { id: 24, category: 'Data Structures', difficulty: 'Medium', question: 'What is a graph vertex?', answer: 'A node in a graph', explanation: 'Vertices represent entities and edges represent relationships between them.' },
    { id: 25, category: 'Data Structures', difficulty: 'Hard', question: 'What property defines a min-heap?', answer: 'Each parent is no greater than its children', explanation: 'The minimum element is kept at the root of a min-heap.' },
    { id: 26, category: 'Data Structures', difficulty: 'Medium', question: 'What is a trie useful for?', answer: 'Prefix-based string lookup', explanation: 'Tries share prefixes and support efficient autocomplete and dictionary queries.' },
    { id: 27, category: 'Data Structures', difficulty: 'Easy', question: 'What does a set typically guarantee?', answer: 'Unique elements', explanation: 'Sets model collections where duplicate values are not retained.' },
    { id: 28, category: 'Algorithms', difficulty: 'Easy', question: 'What is the purpose of binary search?', answer: 'Find a value in a sorted collection efficiently', explanation: 'Binary search halves the remaining search range on each comparison.' },
    { id: 29, category: 'Algorithms', difficulty: 'Medium', question: 'What is the average complexity of quicksort?', answer: 'O(n log n)', explanation: 'Balanced partitions produce logarithmic recursion depth on average.' },
    { id: 30, category: 'Algorithms', difficulty: 'Hard', question: 'When is dynamic programming useful?', answer: 'When overlapping subproblems have optimal substructure', explanation: 'DP stores subproblem results to avoid repeated work.' },
    { id: 31, category: 'Algorithms', difficulty: 'Medium', question: 'What does breadth-first search use to manage frontier nodes?', answer: 'A queue', explanation: 'A queue processes graph levels in discovery order.' },
    { id: 32, category: 'Algorithms', difficulty: 'Medium', question: 'What does depth-first search commonly use?', answer: 'A stack or recursion', explanation: 'DFS explores one branch deeply before backtracking.' },
    { id: 33, category: 'Algorithms', difficulty: 'Hard', question: 'What is a stable sort?', answer: 'A sort that preserves equal-item order', explanation: 'Stability matters when sorting records by multiple fields.' },
    { id: 34, category: 'Algorithms', difficulty: 'Easy', question: 'What does Big O describe?', answer: 'Growth of resource use as input grows', explanation: 'Big O describes an upper-bound growth rate while ignoring constants.' },
    { id: 35, category: 'DBMS', difficulty: 'Easy', question: 'What is a primary key?', answer: 'A unique identifier for a row', explanation: 'A primary key must uniquely identify records and cannot be null.' },
    { id: 36, category: 'DBMS', difficulty: 'Medium', question: 'What is a foreign key used for?', answer: 'Representing a relationship to another table', explanation: 'Foreign keys reference candidate keys and help enforce referential integrity.' },
    { id: 37, category: 'DBMS', difficulty: 'Medium', question: 'What does ACID atomicity mean?', answer: 'A transaction succeeds fully or not at all', explanation: 'Atomicity prevents partially applied transactions.' },
    { id: 38, category: 'DBMS', difficulty: 'Hard', question: 'Why are indexes used?', answer: 'To speed up data retrieval', explanation: 'Indexes add lookup structures, trading storage and write cost for faster reads.' },
    { id: 39, category: 'DBMS', difficulty: 'Medium', question: 'What does a SQL JOIN do?', answer: 'Combines related rows from tables', explanation: 'JOINs use matching conditions to produce a combined result set.' },
    { id: 40, category: 'DBMS', difficulty: 'Hard', question: 'What is a database transaction isolation level?', answer: 'The visibility rules for concurrent transactions', explanation: 'Isolation levels balance consistency against concurrency and performance.' },
    { id: 41, category: 'DBMS', difficulty: 'Easy', question: 'What does SQL GROUP BY do?', answer: 'Groups rows for aggregate calculations', explanation: 'GROUP BY lets functions such as COUNT and AVG operate per group.' },
    { id: 42, category: 'Python', difficulty: 'Easy', question: 'What is a Python list?', answer: 'An ordered mutable collection', explanation: 'Lists can grow, shrink, and hold values of different types.' },
    { id: 43, category: 'Python', difficulty: 'Medium', question: 'What is a Python tuple?', answer: 'An ordered immutable collection', explanation: 'Tuples cannot be changed after creation and can be used as stable records.' },
    { id: 44, category: 'Python', difficulty: 'Medium', question: 'What is a list comprehension?', answer: 'A concise expression that builds a list', explanation: 'It combines iteration and optional filtering into readable list creation.' },
    { id: 45, category: 'Python', difficulty: 'Hard', question: 'What does a decorator do?', answer: 'Wraps a function or class to extend behavior', explanation: 'Decorators apply reusable behavior without editing the wrapped definition.' },
    { id: 46, category: 'Python', difficulty: 'Easy', question: 'What is the purpose of a virtual environment?', answer: 'Isolate project dependencies', explanation: 'Virtual environments prevent packages for one project from affecting another.' },
    { id: 47, category: 'Python', difficulty: 'Medium', question: 'What does yield create in a Python function?', answer: 'A generator that produces values lazily', explanation: 'yield pauses execution and resumes it when the next value is requested.' },
    { id: 48, category: 'Python', difficulty: 'Hard', question: 'What is duck typing?', answer: 'Using an object based on supported behavior', explanation: 'Python often cares about what an object can do rather than its declared type.' },
    { id: 49, category: 'JavaScript', difficulty: 'Medium', question: 'What is debouncing used for?', answer: 'Delaying repeated work until input settles', explanation: 'Debouncing is useful for search fields and resize handlers.' },
    { id: 50, category: 'Algorithms', difficulty: 'Hard', question: 'What is the purpose of a topological sort?', answer: 'Order vertices in a directed acyclic graph by dependencies', explanation: 'Each prerequisite appears before the node that depends on it.' }
  ];
  const getUser = () => JSON.parse(localStorage.getItem('interviewai-user') || JSON.stringify(defaultUser));
  const saveUser = user => localStorage.setItem('interviewai-user', JSON.stringify(user));
  const showToast = message => { const toast = document.querySelector('#toast'); if (!toast) return; toast.textContent = message; toast.classList.add('show'); clearTimeout(window.toastTimer); window.toastTimer = setTimeout(() => toast.classList.remove('show'), 2600); };
  const initTheme = () => { const saved = localStorage.getItem('interviewai-theme'); if (saved === 'light') document.body.classList.add('light-theme'); document.querySelectorAll('[data-theme-toggle]').forEach(button => button.addEventListener('click', () => { document.body.classList.toggle('light-theme'); localStorage.setItem('interviewai-theme', document.body.classList.contains('light-theme') ? 'light' : 'dark'); showToast('Theme updated'); })); };
  const initMobileNav = () => document.querySelectorAll('.mobile-menu').forEach(button => button.addEventListener('click', () => { const sidebar = document.querySelector('.sidebar'); if (sidebar) sidebar.classList.toggle('open'); }));
  const initHeader = () => { const header = document.querySelector('.site-header'); if (header) window.addEventListener('scroll', () => header.classList.toggle('scrolled', window.scrollY > 20)); };
  const init = () => { initTheme(); initMobileNav(); initHeader(); const user = getUser(); document.querySelectorAll('#sideUser').forEach(el => el.textContent = user.name); document.querySelectorAll('#greetingName').forEach(el => el.textContent = user.name.split(' ')[0]); };
  return { questions, getUser, saveUser, showToast, init };
})();
document.addEventListener('DOMContentLoaded', InterviewAI.init);
