document.addEventListener('DOMContentLoaded', () => {
  const setup = document.querySelector('#setupPanel'); const room = document.querySelector('#roomPanel'); const start = document.querySelector('#startInterview'); const next = document.querySelector('#nextQuestion'); const skip = document.querySelector('#skipQuestion'); const questionTitle = document.querySelector('#interviewQuestion'); const answer = document.querySelector('#interviewAnswer'); const progress = document.querySelector('#roomProgress'); const progressBar = document.querySelector('#roomProgressBar'); const timer = document.querySelector('#timer');
  let current = 0; let sessionQuestions = []; let seconds = 600; let interval;
  function render() { const item = sessionQuestions[current]; questionTitle.textContent = item.question; progress.textContent = `Question ${current + 1} / ${sessionQuestions.length}`; progressBar.style.width = `${((current + 1) / sessionQuestions.length) * 100}%`; answer.value = ''; }
  function finish() { clearInterval(interval); const responses = JSON.parse(localStorage.getItem('interviewai-interview') || '{}'); const score = Math.max(65, Math.min(96, 70 + Object.values(responses).filter(Boolean).length * 4)); localStorage.setItem('interviewai-progress', JSON.stringify({ attempted: 128 + sessionQuestions.length, score, mocks: 13 })); InterviewAI.showToast('Interview complete. Your signal is saved.'); setTimeout(() => { window.location.href = 'results.html'; }, 800); }
  function advance() { const responses = JSON.parse(localStorage.getItem('interviewai-interview') || '{}'); responses[current] = answer.value.trim(); localStorage.setItem('interviewai-interview', JSON.stringify(responses)); if (current === sessionQuestions.length - 1) finish(); else { current += 1; render(); } }
  start.addEventListener('click', () => { const amount = Number(document.querySelector('#numberSelect').value); sessionQuestions = [...InterviewAI.questions].sort(() => Math.random() - .5).slice(0, amount); setup.classList.add('hidden'); room.classList.remove('hidden'); render(); interval = setInterval(() => { seconds -= 1; timer.textContent = `${String(Math.floor(seconds / 60)).padStart(2, '0')}:${String(seconds % 60).padStart(2, '0')}`; if (seconds <= 60) timer.classList.add('warning'); if (seconds <= 0) finish(); }, 1000); });
  next.addEventListener('click', advance); skip.addEventListener('click', () => { answer.value = ''; advance(); });
});
